version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_diginext
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: